### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by daplcor** [eckoDAO-org/ecko-dex-ui#263]
https://github.com/eckoDAO-org/ecko-dex-ui/blob/7699610be41917c2676b3db80f9d83ba2ab96784/src/contexts/SwapContext.js#L46

I was looking over some of the dex code and noticed this (older?) code was in here.  I'm not sure if there is a use still that isn't obvious, but leaving any functions that would call a privateKey would be good to consider removing.  It's more in case someone else comes across this and isn't aware, the other functions are great for people to see!

**Comment by peppinho89** [comment]
Thanks for the report. We removed the unused function here and closing the issue: [https://github.com/eckoDAO-org/ecko-dex-ui/pull/264/commits/838db20567a5f2eb56cc10ef18a0fcdd566e8257](https://github.com/eckoDAO-org/ecko-dex-ui/pull/264/commits/838db20567a5f2eb56cc10ef18a0fcdd566e8257)
